name: "Cygwin"

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  cygwin:
    name: "cygwin, release"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Cygwin Base
        run: |
          choco install --no-progress cygwin
      - name: Install Cygwin Packages
        run: |
          C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P gcc-core,gcc-g++,make,cmake
        shell: cmd
      - name: Configure
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_BENCHMARKING=ON -DCMAKE_INSTALL_PREFIX=/usr ."
        shell: cmd
      - name: Build
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "make all"
        shell: cmd
      - name: Test
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "make check"
        shell: cmd
      - name: Run Benchmarks
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "make bench"
        shell: cmd
      - name: Run Examples
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "make examples"
        shell: cmd
      - name: Install
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "make install"
        shell: cmd
      - name: Test Build with Install
        run: |
          path C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          bash.exe -c "gcc docs/examples/basic/basic_example.c -lstumpless -o run_example.exe && ./run_example.exe"
        shell: cmd
